

show PDBS;


CREATE USER PRY2205_USER1 
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER1 ;

GRANT RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PUBLIC SYNONYM TO PRY2205_USER1 ;

ALTER USER PRY2205_USER1  DEFAULT ROLE RESOURCE;

CREATE OR REPLACE PUBLIC SYNONYM S_ALUMNO    FOR PRY2205_USER1.ALUMNO;
CREATE OR REPLACE PUBLIC SYNONYM S_CARRERA   FOR PRY2205_USER1.CARRERA;
CREATE OR REPLACE PUBLIC SYNONYM S_LIBRO     FOR PRY2205_USER1.LIBRO;
CREATE OR REPLACE PUBLIC SYNONYM S_AUTOR     FOR PRY2205_USER1.AUTOR;
CREATE OR REPLACE PUBLIC SYNONYM S_EDITORIAL FOR PRY2205_USER1.EDITORIAL;
CREATE OR REPLACE PUBLIC SYNONYM S_ESCUELA   FOR PRY2205_USER1.ESCUELA;
CREATE OR REPLACE PUBLIC SYNONYM S_EJEMPLAR  FOR PRY2205_USER1.EJEMPLAR;
CREATE OR REPLACE PUBLIC SYNONYM S_PRESTAMO  FOR PRY2205_USER1.PRESTAMO;

CREATE OR REPLACE SYNONYM S_VALOR_MULTA  FOR VALOR_MULTA_PRESTAMO;
CREATE OR REPLACE SYNONYM S_REBAJA_MULTA FOR REBAJA_MULTA;
CREATE OR REPLACE SYNONYM S_DET_MENSUAL  FOR DETALLE_PRESTAMO_MENSUAL;
CREATE OR REPLACE SYNONYM S_RES_MENSUAL  FOR RESUMEN_PRESTAMO_MENSUAL;
CREATE OR REPLACE SYNONYM S_ERROR_PREST  FOR ERROR_PROCESO_PRESTAMO;

CREATE USER PRY2205_USER2 IDENTIFIED BY "PRY2205.semana_8";

GRANT CREATE SESSION TO PRY2205_USER2;
GRANT CREATE TABLE TO PRY2205_USER2;
GRANT CREATE SEQUENCE TO PRY2205_USER2;
GRANT CREATE TRIGGER TO PRY2205_USER2;
GRANT CREATE PROCEDURE TO PRY2205_USER2;
GRANT CREATE VIEW TO PRY2205_USER2;
GRANT CREATE SYNONYM TO PRY2205_USER2;
GRANT CREATE TYPE TO PRY2205_USER2;
ALTER USER PRY2205_USER2 QUOTA 500M ON USERS;

GRANT ALTER ANY TABLE TO PRY2205_USER2;
GRANT DROP ANY TABLE TO PRY2205_USER2;
GRANT ALTER ANY SEQUENCE TO PRY2205_USER2;
GRANT DROP ANY SEQUENCE TO PRY2205_USER2;
GRANT SELECT ANY TABLE TO PRY2205_USER2;

GRANT CREATE ANY SYNONYM TO PRY2205_USER2;


CREATE ROLE PRY2205_ROL_D;


CREATE ROLE PRY2205_ROL_P;

GRANT PRY2205_ROL_D TO PRY2205_USER1;

GRANT PRY2205_ROL_P TO PRY2205_USER2;

GRANT CREATE SESSION TO PRY2205_ROL_D;
GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE SEQUENCE TO PRY2205_ROL_D;
GRANT CREATE TRIGGER TO PRY2205_ROL_D;
GRANT CREATE PROCEDURE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE TYPE TO PRY2205_ROL_D;

GRANT ALTER ANY TABLE TO PRY2205_ROL_D;
GRANT DROP ANY TABLE TO PRY2205_ROL_D;
GRANT SELECT ANY TABLE TO PRY2205_ROL_D;
GRANT INSERT ANY TABLE TO PRY2205_ROL_D;
GRANT UPDATE ANY TABLE TO PRY2205_ROL_D;
GRANT DELETE ANY TABLE TO PRY2205_ROL_D;

GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;
GRANT DROP PUBLIC SYNONYM TO PRY2205_ROL_D;
GRANT SELECT ANY DICTIONARY TO PRY2205_ROL_D;

GRANT CREATE SESSION TO PRY2205_ROL_P;

GRANT CREATE TABLE TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT CREATE TRIGGER TO PRY2205_ROL_P;
GRANT CREATE VIEW TO PRY2205_ROL_P;
GRANT CREATE SYNONYM TO PRY2205_ROL_P;

GRANT CREATE ANY SYNONYM TO PRY2205_ROL_P;
GRANT SELECT ANY TABLE TO PRY2205_ROL_P;



