-- Caso 1 creacion de usuario --

-- Creacion del primer usuari con sus respectivos privilegios --
CREATE USER PRY2205_EFT
IDENTIFIED BY "PRY2205.semana_9"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE TABLE, CREATE INDEX, CREATE VIEW, CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM, CREATE SYNONYM TO PRY2205_EFT;
ALTER USER PRY2205_EFT QUOTA UNLIMITED ON DATA;

-- Creacion del segundo usuario con sus respectivos privilegios--
CREATE USER PRY2205_EFT_DES 
IDENTIFIED BY "PRY2205.semana_91"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE VIEW, CREATE PROFILE, CREATE USER TO PRY2205_EFT_DES;


-- Creacion del tercer usuario con sus respectivos privilegios--
CREATE USER PRY2205_EFT_CON 
IDENTIFIED BY "PRY2205.semana_92"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

GRANT CREATE SESSION TO PRY2205_EFT_CON;

-- Se crean los roles solicitados--
CREATE ROLE PRY2205_ROL_D;

CREATE ROLE PRY2205_ROL_CON;

-- Se asignan permisos a los roles segun lo solicitado--

GRANT CREATE SESSION TO PRY2205_ROL_D;
GRANT CREATE VIEW, CREATE PROFILE, CREATE USER TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;

-- Rol para consulta
GRANT CREATE SESSION TO PRY2205_ROL_CON;

-- Se asigno rol segun solicitud--

GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_CON TO PRY2205_EFT_CON;


-- Se crean los sinonimos para el Caso 2 --

CREATE PUBLIC SYNONYM PROFESIONALES_SYN FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM PROFESION_SYN FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM ISAPRE_SYN FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM RANGOS_SUELDOS_SYN FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE PUBLIC SYNONYM TIPO_CONTRATO_SYN FOR PRY2205_EFT.TIPO_CONTRATO;

-- Se otorgan permisos a PRY2205_EFT_DES segun solicitud--

GRANT SELECT, INSERT, UPDATE, DELETE ON PROFESIONAL TO PRY2205_EFT_DES;
GRANT SELECT ON PROFESION TO PRY2205_EFT_DES;
GRANT SELECT ON ISAPRE TO PRY2205_EFT_DES;
GRANT SELECT ON RANGOS_SUELDOS TO PRY2205_EFT_DES;
GRANT SELECT ON TIPO_CONTRATO TO PRY2205_EFT_DES;
GRANT SELECT, INSERT, UPDATE, DELETE ON CARTOLA_PROFESIONALES TO PRY2205_EFT_DES;

-- Creacion del informe y nueva Tabla para el Caso 2--

INSERT INTO PRY2205_EFT.CARTOLA_PROFESIONALES
SELECT 
    p.RUTPROF AS RUT_PROFESIONAL,
    INITCAP(p.NOMPRO) || ' ' || INITCAP(p.APPPRO) || ' ' || INITCAP(p.APMPRO) AS NOMBRE_PROFESIONAL,
    pr.NOMPROFESION AS PROFESION,
    i.NOMISAPRE AS ISAPRE,
    p.SUELDO AS SUELDO_BASE,
    NVL(p.COMISION, 0) AS PORC_COMISION_PROFESIONAL,
    NVL(p.SUELDO * p.COMISION, 0) AS VALOR_TOTAL_COMISION,
    NVL((
        SELECT rs.HONOR_PCT 
        FROM RANGOS_SUELDOS_SYN rs
        WHERE p.SUELDO BETWEEN rs.S_MIN AND rs.S_MAX
    ), 0) AS PORCENTATE_HONORARIO,
    CASE 
        WHEN tc.NOMTCONTRATO = 'Indefinido Jornada Completa' THEN 150000
        WHEN tc.NOMTCONTRATO = 'Indefinido Jornada Parcial' THEN 120000
        WHEN tc.NOMTCONTRATO = 'Plazo fijo' THEN 60000
        WHEN tc.NOMTCONTRATO = 'Honorarios' THEN 50000
        ELSE 0
    END AS BONO_MOVILIZACION,
    p.SUELDO + 
    NVL(p.SUELDO * p.COMISION, 0) + 
    (p.SUELDO * NVL((
        SELECT rs.HONOR_PCT/100 
        FROM RANGOS_SUELDOS_SYN rs
        WHERE p.SUELDO BETWEEN rs.S_MIN AND rs.S_MAX
    ), 0)) +
    CASE 
        WHEN tc.NOMTCONTRATO = 'Indefinido Jornada Completa' THEN 150000
        WHEN tc.NOMTCONTRATO = 'Indefinido Jornada Parcial' THEN 120000
        WHEN tc.NOMTCONTRATO = 'Plazo fijo' THEN 60000
        WHEN tc.NOMTCONTRATO = 'Honorarios' THEN 50000
        ELSE 0
    END AS TOTAL_PAGAR
FROM 
    PROFESIONALES_SYN p
    INNER JOIN PROFESION_SYN pr ON p.IDPROFESION = pr.IDPROFESION
    INNER JOIN ISAPRE_SYN i ON p.IDISAPRE = i.IDISAPRE
    INNER JOIN TIPO_CONTRATO_SYN tc ON p.IDTCONTRATO = tc.IDTCONTRATO
ORDER BY 
    pr.NOMPROFESION,
    p.SUELDO DESC,
    NVL(p.COMISION, 0),
    p.RUTPROF;
CREATE OR REPLACE VIEW PRY2205_EFT.VW_ANALISIS_PROFESIONALES AS
SELECT 
    'ALTO SUELDO' AS CATEGORIA,
    p.RUTPROF,
    INITCAP(p.NOMPRO) || ' ' || INITCAP(p.APPPRO) AS NOMBRE_COMPLETO,
    pr.NOMPROFESION AS PROFESION,
    p.SUELDO AS SUELDO_BASE,
    NVL(p.COMISION, 0) AS COMISION,
    'ALTA REMUNERACION' AS OBSERVACION
FROM 
    PROFESIONALES_SYN p
    INNER JOIN PROFESION_SYN pr ON p.IDPROFESION = pr.IDPROFESION
WHERE 
    p.SUELDO > (SELECT AVG(SUELDO) * 1.2 FROM PROFESIONALES_SYN)

UNION ALL

SELECT 
    'ALTA COMISION' AS CATEGORIA,
    p.RUTPROF,
    INITCAP(p.NOMPRO) || ' ' || INITCAP(p.APPPRO) AS NOMBRE_COMPLETO,
    pr.NOMPROFESION AS PROFESION,
    p.SUELDO AS SUELDO_BASE,
    NVL(p.COMISION, 0) AS COMISION,
    'ALTO PORCENTAJE COMISION' AS OBSERVACION
FROM 
    PROFESIONALES_SYN p
    INNER JOIN PROFESION_SYN pr ON p.IDPROFESION = pr.IDPROFESION
WHERE 
    NVL(p.COMISION, 0) > 0.1

UNION
SELECT 
    'ALTO SUELDO Y COMISION' AS CATEGORIA,
    p.RUTPROF,
    INITCAP(p.NOMPRO) || ' ' || INITCAP(p.APPPRO) AS NOMBRE_COMPLETO,
    pr.NOMPROFESION AS PROFESION,
    p.SUELDO AS SUELDO_BASE,
    NVL(p.COMISION, 0) AS COMISION,
    'EXCELENTE DESEMPEÑO' AS OBSERVACION
FROM 
    PROFESIONALES_SYN p
    INNER JOIN PROFESION_SYN pr ON p.IDPROFESION = pr.IDPROFESION
WHERE 
    p.SUELDO > (SELECT AVG(SUELDO) * 1.2 FROM PROFESIONALES_SYN)
    AND NVL(p.COMISION, 0) > 0.1

ORDER BY 
    CATEGORIA, 
    SUELDO_BASE DESC;    
 commit;    

-- Se crea sininimo de la nueva vista--

CREATE PUBLIC SYNONYM CARTOLA_SYN FOR PRY2205_EFT.CARTOLA_PROFESIONALES;

-- Se otorgan permisos a PRY2205_EFT_CON segun nueva vista--

GRANT SELECT ON CARTOLA_SYN TO PRY2205_EFT_CON;

-- Comando para revisar la solicitud desde usuario PRY2205_EFT_CON--

SELECT * FROM CARTOLA_SYN WHERE ROWNUM <= 10;


--Caso 3.1: Creación de Vista --

-- Creacion de la vista para el Caso 3.1--   
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT 
    e.IDEMPRESA,
    TO_CHAR(e.RUT_EMPRESA) || '-' || e.DV_EMPRESA AS RUT_EMPRESA,
    UPPER(e.NOMEMPRESA) AS NOMBRE_EMPRESA,
    -- Años de antigüedad calculados desde fecha inicio actividades
    TRUNC(MONTHS_BETWEEN(SYSDATE, e.FECHA_INICIACION_ACTIVIDADES)/12) AS ANIOS_ANTIGUEDAD,
    e.IVA_DECLARADO,
    
    COUNT(a.IDEMPRESA) AS TOTAL_ASESORIAS_ANUAL,
    ROUND(COUNT(a.IDEMPRESA)/12, 2) AS ASESORIAS_PROMEDIO_MENSUAL,
    
    ROUND(e.IVA_DECLARADO * (COUNT(a.IDEMPRESA)/12) / 100, 2) AS DEVOLUCION_IVA_ESTIMADA,
    
    CASE 
        WHEN ROUND(COUNT(a.IDEMPRESA)/12, 2) > 5 THEN 'CLIENTE PREMIUM'
        WHEN ROUND(COUNT(a.IDEMPRESA)/12, 2) BETWEEN 3 AND 5 THEN 'CLIENTE'
        ELSE 'CLIENTE POCO CONCURRIDO'
    END AS TIPO_CLIENTE,
    
    CASE 
        WHEN ROUND(COUNT(a.IDEMPRESA)/12, 2) > 5 AND 
             COUNT(a.IDEMPRESA) >= 7 THEN '1 ASESORÍA GRATIS'
        WHEN ROUND(COUNT(a.IDEMPRESA)/12, 2) > 5 AND 
             COUNT(a.IDEMPRESA) < 7 THEN '1 ASESORÍA 40% DE DESCUENTO'

        WHEN ROUND(COUNT(a.IDEMPRESA)/12, 2) BETWEEN 3 AND 5 AND 
             COUNT(a.IDEMPRESA) = 5 THEN '1 ASESORÍA 30% DE DESCUENTO'
        WHEN ROUND(COUNT(a.IDEMPRESA)/12, 2) BETWEEN 3 AND 5 AND 
             COUNT(a.IDEMPRESA) < 5 THEN '1 ASESORÍA 20% DE DESCUENTO'
        
        ELSE 'CAPTAR CLIENTE'
    END AS PROMOCION_RECOMENDACION,
    
    EXTRACT(YEAR FROM SYSDATE) - 1 AS ANIO_CONSULTA,
    SYSDATE AS FECHA_CREACION_VISTA
    
FROM 
    EMPRESA e
    LEFT JOIN ASESORIA a ON e.IDEMPRESA = a.IDEMPRESA
    
WHERE 
    a.FIN IS NOT NULL 
    AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
    
GROUP BY 
    e.IDEMPRESA,
    e.RUT_EMPRESA,
    e.DV_EMPRESA,
    e.NOMEMPRESA,
    e.FECHA_INICIACION_ACTIVIDADES,
    e.IVA_DECLARADO
    
HAVING 
    COUNT(a.IDEMPRESA) > 0
    
ORDER BY 
    UPPER(e.NOMEMPRESA) ASC;
        commit;
    
--Revisar Vista--    
    SELECT 
    RUT_EMPRESA,
    NOMBRE_EMPRESA,
    ANIOS_ANTIGUEDAD,
    TOTAL_ASESORIAS_ANUAL,
    ASESORIAS_PROMEDIO_MENSUAL,
    TIPO_CLIENTE,
    PROMOCION_RECOMENDACION
FROM VW_EMPRESAS_ASESORADAS
WHERE ROWNUM <= 10;

-- Ver estructura de la vista--
DESC VW_EMPRESAS_ASESORADAS;


-- Nuevo sinonimos para el caso 3.1--

CREATE OR REPLACE PUBLIC SYNONYM EMPRESA_SYN FOR PRY2205_EFT.EMPRESA;
CREATE OR REPLACE PUBLIC SYNONYM ASESORIA_SYN FOR PRY2205_EFT.ASESORIA;
CREATE OR REPLACE PUBLIC SYNONYM VW_EMPRESAS_ASESORADAS_SYN FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

-- Se otorgan permisos a PRY2205_EFT_CON segun nueva vista--

GRANT SELECT ON VW_EMPRESAS_ASESORADAS_SYN TO PRY2205_EFT_CON;

-- Comando para revisar la solicitud desde usuario PRY2205_EFT_CON--

SELECT * FROM VW_EMPRESAS_ASESORADAS_SYN WHERE ROWNUM <= 5;

--Caso 3.2: Creación de Índices --
CREATE INDEX IDX_ASESORIA_EMPRESA_ANIO 
ON ASESORIA (IDEMPRESA, EXTRACT(YEAR FROM FIN))
COMPUTE STATISTICS;

CREATE INDEX IDX_EMPRESA_NOMBRE 
ON EMPRESA (UPPER(NOMEMPRESA), IDEMPRESA)
COMPUTE STATISTICS;

-- Verificacion de los indices creados --
SELECT index_name, table_name, uniqueness 
FROM user_indexes 
WHERE table_name IN ('EMPRESA', 'ASESORIA')
ORDER BY table_name, index_name;







