-- Caso 1 creacion de usuario --

show PDBS;


CREATE USER PRY2205_USER1 
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER1 ;

GRANT RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PUBLIC SYNONYM TO PRY2205_USER1 ;

ALTER USER PRY2205_USER1  DEFAULT ROLE RESOURCE;

CREATE OR REPLACE PUBLIC SYNONYM S_ALUMNO    FOR PRY2205_USER1.ALUMNO;
CREATE OR REPLACE PUBLIC SYNONYM S_CARRERA   FOR PRY2205_USER1.CARRERA;
CREATE OR REPLACE PUBLIC SYNONYM S_LIBRO     FOR PRY2205_USER1.LIBRO;
CREATE OR REPLACE PUBLIC SYNONYM S_AUTOR     FOR PRY2205_USER1.AUTOR;
CREATE OR REPLACE PUBLIC SYNONYM S_EDITORIAL FOR PRY2205_USER1.EDITORIAL;
CREATE OR REPLACE PUBLIC SYNONYM S_ESCUELA   FOR PRY2205_USER1.ESCUELA;
CREATE OR REPLACE PUBLIC SYNONYM S_EJEMPLAR  FOR PRY2205_USER1.EJEMPLAR;
CREATE OR REPLACE PUBLIC SYNONYM S_PRESTAMO  FOR PRY2205_USER1.PRESTAMO;

CREATE OR REPLACE SYNONYM S_VALOR_MULTA  FOR VALOR_MULTA_PRESTAMO;
CREATE OR REPLACE SYNONYM S_REBAJA_MULTA FOR REBAJA_MULTA;
CREATE OR REPLACE SYNONYM S_DET_MENSUAL  FOR DETALLE_PRESTAMO_MENSUAL;
CREATE OR REPLACE SYNONYM S_RES_MENSUAL  FOR RESUMEN_PRESTAMO_MENSUAL;
CREATE OR REPLACE SYNONYM S_ERROR_PREST  FOR ERROR_PROCESO_PRESTAMO;

CREATE USER PRY2205_USER2 IDENTIFIED BY "PRY2205.semana_8";

GRANT CREATE SESSION TO PRY2205_USER2;
GRANT CREATE TABLE TO PRY2205_USER2;
GRANT CREATE SEQUENCE TO PRY2205_USER2;
GRANT CREATE TRIGGER TO PRY2205_USER2;
GRANT CREATE PROCEDURE TO PRY2205_USER2;
GRANT CREATE VIEW TO PRY2205_USER2;
GRANT CREATE SYNONYM TO PRY2205_USER2;
GRANT CREATE TYPE TO PRY2205_USER2;
ALTER USER PRY2205_USER2 QUOTA 500M ON USERS;

GRANT ALTER ANY TABLE TO PRY2205_USER2;
GRANT DROP ANY TABLE TO PRY2205_USER2;
GRANT ALTER ANY SEQUENCE TO PRY2205_USER2;
GRANT DROP ANY SEQUENCE TO PRY2205_USER2;
GRANT SELECT ANY TABLE TO PRY2205_USER2;

GRANT CREATE ANY SYNONYM TO PRY2205_USER2;


CREATE ROLE PRY2205_ROL_D;


CREATE ROLE PRY2205_ROL_P;

GRANT PRY2205_ROL_D TO PRY2205_USER1;

GRANT PRY2205_ROL_P TO PRY2205_USER2;

GRANT CREATE SESSION TO PRY2205_ROL_D;
GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE SEQUENCE TO PRY2205_ROL_D;
GRANT CREATE TRIGGER TO PRY2205_ROL_D;
GRANT CREATE PROCEDURE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE TYPE TO PRY2205_ROL_D;

GRANT ALTER ANY TABLE TO PRY2205_ROL_D;
GRANT DROP ANY TABLE TO PRY2205_ROL_D;
GRANT SELECT ANY TABLE TO PRY2205_ROL_D;
GRANT INSERT ANY TABLE TO PRY2205_ROL_D;
GRANT UPDATE ANY TABLE TO PRY2205_ROL_D;
GRANT DELETE ANY TABLE TO PRY2205_ROL_D;

GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;
GRANT DROP PUBLIC SYNONYM TO PRY2205_ROL_D;
GRANT SELECT ANY DICTIONARY TO PRY2205_ROL_D;

GRANT CREATE SESSION TO PRY2205_ROL_P;

GRANT CREATE TABLE TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT CREATE TRIGGER TO PRY2205_ROL_P;
GRANT CREATE VIEW TO PRY2205_ROL_P;
GRANT CREATE SYNONYM TO PRY2205_ROL_P;

GRANT CREATE ANY SYNONYM TO PRY2205_ROL_P;
GRANT SELECT ANY TABLE TO PRY2205_ROL_P;

-- Caso 2 --

CREATE SEQUENCE SEQ_CONTROL_STOCK
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO CONTROL_STOCK_LIBROS
SELECT
    ROW_NUMBER() OVER (ORDER BY libroid) AS correlativo,
    fecha_proceso,
    libroid,
    nombre_libro,
    total_ejemplares,
    ejemplares_prestados,
    ejemplares_disponibles,
    porcentaje_prestamo,
    stock_critico
FROM (
    SELECT
        TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'MM/YYYY') AS fecha_proceso,
        l.libroid,
        l.nombre_libro,
        COUNT(DISTINCT e.ejemplarid) AS total_ejemplares,
        COUNT(DISTINCT p.ejemplarid) AS ejemplares_prestados,
        COUNT(DISTINCT e.ejemplarid) - COUNT(DISTINCT p.ejemplarid) AS ejemplares_disponibles,
        ROUND((COUNT(DISTINCT p.ejemplarid) / NULLIF(COUNT(DISTINCT e.ejemplarid), 0)) * 100, 2) AS porcentaje_prestamo,
        CASE
            WHEN COUNT(DISTINCT e.ejemplarid) - COUNT(DISTINCT p.ejemplarid) > 2 THEN 'S'
            ELSE 'N'
        END AS stock_critico
    FROM libro l
    JOIN ejemplar e ON l.libroid = e.libroid
    LEFT JOIN prestamo p ON e.libroid = p.libroid 
        AND e.ejemplarid = p.ejemplarid
        AND EXTRACT(YEAR FROM p.fecha_inicio) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -24))
        AND p.empleadoid IN (190, 180, 150)
        AND p.fecha_inicio >= TRUNC(ADD_MONTHS(SYSDATE, -24), 'YEAR')
        AND p.fecha_inicio < TRUNC(ADD_MONTHS(SYSDATE, -12), 'YEAR')
    GROUP BY l.libroid, l.nombre_libro
);

COMMIT;

-- Caso 3 --

CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT 
    p.prestamoid AS "ID_PRÉSTAMO",
    a.nombre || ' ' || a.apaterno || ' ' || a.amaterno AS "NOMBRE_ALUMNO",
    c.descripcion AS "CARRERA",
    l.libroid AS "CÓDIGO_LIBRO",
    l.precio AS "PRECIO_LIBRO",
    p.fecha_termino AS "FECHA_TÉRMINO",
    p.fecha_entrega AS "FECHA_ENTREGA",
    GREATEST(TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino), 0) AS "DÍAS_ATRASO",
    ROUND(l.precio * 0.03 * GREATEST(TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino), 0), 2) AS "MULTA_CALCULADA",
    NVL(rm.porc_rebaja_multa, 0) AS "%_REBAJA",
    ROUND(
        (l.precio * 0.03 * GREATEST(TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino), 0)) * 
        (1 - NVL(rm.porc_rebaja_multa, 0) / 100), 
        2
    ) AS "MULTA_FINAL"
FROM 
    PRESTAMO p
    JOIN alumno a ON p.alumnoid = a.alumnoid
    JOIN CARRERA c ON a.carreraid = c.carreraid
    JOIN libro l ON p.libroid = l.libroid
    LEFT JOIN REBAJA_MULTA rm ON c.carreraid = rm.carreraid
WHERE 
    EXTRACT(YEAR FROM p.fecha_termino) = EXTRACT(YEAR FROM SYSDATE) - 2
    AND p.fecha_entrega > p.fecha_termino
ORDER BY 
    p.fecha_entrega DESC;
    
-- Caso 3.1 --

CREATE INDEX IX_PRESTAMO_EJEMPLAR ON PRESTAMO (LIBROID, EJEMPLARID);


CREATE INDEX IX_PRESTAMO_ALUMNO ON PRESTAMO (ALUMNOID);


CREATE INDEX IX_ALUMNO_CARRERA ON ALUMNO (CARRERAID);

