
CREATE USER PRY2205_USER2 IDENTIFIED BY "PRY2205.semana_8";

GRANT CREATE SESSION TO PRY2205_USER2;
GRANT CREATE TABLE TO PRY2205_USER2;
GRANT CREATE SEQUENCE TO PRY2205_USER2;
GRANT CREATE TRIGGER TO PRY2205_USER2;
GRANT CREATE PROCEDURE TO PRY2205_USER2;
GRANT CREATE VIEW TO PRY2205_USER2;
GRANT CREATE SYNONYM TO PRY2205_USER2;
GRANT CREATE TYPE TO PRY2205_USER2;

GRANT ALTER ANY TABLE TO PRY2205_USER2;
GRANT DROP ANY TABLE TO PRY2205_USER2;
GRANT ALTER ANY SEQUENCE TO PRY2205_USER2;
GRANT DROP ANY SEQUENCE TO PRY2205_USER2;

GRANT CREATE ANY SYNONYM TO PRY2205_USER2;

CREATE PUBLIC SYNONYM libro FOR PRY2205_USER1.libro;
CREATE PUBLIC SYNONYM ejemplar FOR PRY2205_USER1.ejemplar;
CREATE PUBLIC SYNONYM prestamo FOR PRY2205_USER1.prestamo;
CREATE PUBLIC SYNONYM empleado FOR PRY2205_USER1.empleado;

CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT 
    p.prestamoid AS "ID_PRÉSTAMO",
    a.nombre || ' ' || a.apaterno || ' ' || a.amaterno AS "NOMBRE_ALUMNO",
    c.descripcion AS "CARRERA",
    l.libroid AS "CÓDIGO_LIBRO",
    l.precio AS "PRECIO_LIBRO",
    p.fecha_termino AS "FECHA_TÉRMINO",
    p.fecha_entrega AS "FECHA_ENTREGA",
    GREATEST(TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino), 0) AS "DÍAS_ATRASO",
    ROUND(l.precio * 0.03 * GREATEST(TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino), 0), 2) AS "MULTA_CALCULADA",
    NVL(rm.porc_rebaja_multa, 0) AS "%_REBAJA",
    ROUND(
        (l.precio * 0.03 * GREATEST(TRUNC(p.fecha_entrega) - TRUNC(p.fecha_termino), 0)) * 
        (1 - NVL(rm.porc_rebaja_multa, 0) / 100), 
        2
    ) AS "MULTA_FINAL"
FROM 
    PRESTAMO p
    JOIN alumno a ON p.alumnoid = a.alumnoid
    JOIN CARRERA c ON a.carreraid = c.carreraid
    JOIN libro l ON p.libroid = l.libroid
    LEFT JOIN REBAJA_MULTA rm ON c.carreraid = rm.carreraid
WHERE 
    EXTRACT(YEAR FROM p.fecha_termino) = EXTRACT(YEAR FROM SYSDATE) - 2
    AND p.fecha_entrega > p.fecha_termino
ORDER BY 
    p.fecha_entrega DESC;
    
    

CREATE INDEX IX_PRESTAMO_EJEMPLAR ON PRESTAMO (LIBROID, EJEMPLARID);


CREATE INDEX IX_PRESTAMO_ALUMNO ON PRESTAMO (ALUMNOID);


CREATE INDEX IX_ALUMNO_CARRERA ON ALUMNO (CARRERAID);

